export const LC116_ITEMS = [
    { id: '01.01', description: 'Análise e desenvolvimento de sistemas' },
    { id: '01.02', description: 'Programação' },
    { id: '01.03', description: 'Processamento de dados e congêneres' },
    { id: '01.04', description: 'Elaboração de programas de computadores, inclusive de jogos eletrônicos' },
    { id: '01.05', description: 'Licenciamento ou cessão de direito de uso de programas de computação' },
    { id: '01.06', description: 'Assessoria e consultoria em informática' },
    { id: '01.07', description: 'Suporte técnico em informática, inclusive instalação, configuração e manutenção de programas de computação e bancos de dados' },
    { id: '01.08', description: 'Planejamento, confecção, manutenção e atualização de páginas eletrônicas' },
    { id: '01.09', description: 'Disponibilização, sem cessão definitiva, de conteúdos de áudio, vídeo, imagem e texto por meio da internet' },
    { id: '02.01', description: 'Serviços de pesquisas e desenvolvimento de qualquer natureza' },
    { id: '03.02', description: 'Cessão de direito de uso de marcas e de sinais de propaganda' },
    { id: '03.03', description: 'Exploração de salões de festas, centro de convenções, escritórios virtuais, stands, etc.' },
    { id: '03.05', description: 'Cessão de andaimes, palcos, coberturas e outras estruturas de uso temporário' },
    { id: '04.01', description: 'Medicina e biomedicina' },
    { id: '04.02', description: 'Análises clínicas, patologia, eletricidade médica, radioterapia, etc.' },
    { id: '04.03', description: 'Hospitais, clínicas, sanatórios, manicômios, casas de saúde, etc.' },
    { id: '05.01', description: 'Medicina veterinária e zootecnia' },
    { id: '07.01', description: 'Engenharia, agronomia, agrimensura, arquitetura, geologia, urbanismo, paisagismo, etc.' },
    { id: '07.02', description: 'Execução, por administração, empreitada ou subempreitada, de obras de construção civil, etc.' },
    { id: '07.03', description: 'Elaboração de planos diretores, estudos de viabilidade, estudos organizacionais e outros, etc.' },
    { id: '07.05', description: 'Reforma, conservação, manutenção e pintura de imóveis, pontes, portos e rodovias' },
    { id: '10.01', description: 'Agenciamento, corretagem ou intermediação de câmbio, de seguros, de cartões de crédito, etc.' },
    { id: '10.02', description: 'Agenciamento, corretagem ou intermediação de títulos em geral, valores mobiliários e etc.' },
    { id: '10.05', description: 'Agenciamento, corretagem ou intermediação de bens móveis ou imóveis' },
    { id: '10.08', description: 'Agenciamento de publicidade e propaganda, inclusive o agenciamento de veiculação por qualquer meio' },
    { id: '10.09', description: 'Representação de qualquer natureza, inclusive comercial' },
    { id: '11.02', description: 'Vigilância, segurança ou monitoramento de bens, pessoas e semoventes' },
    { id: '11.04', description: 'Armazenamento, depósito, carga, descarga, arrumação e guarda de bens de qualquer espécie' },
    { id: '13.05', description: 'Composição gráfica, fotocomposição, clicheria, zincografia, litografia, fotolitografia' },
    { id: '14.01', description: 'Lubrificação, limpeza, lustração, revisão, carga e recarga, conserto, restauração, etc.' },
    { id: '14.05', description: 'Restauração, recondicionamento, acondicionamento, pintura, beneficiamento, lavagem, etc.' },
    { id: '17.01', description: 'Assessoria ou consultoria de qualquer natureza, não contida em outros itens' },
    { id: '17.02', description: 'Datilografia, digitação, estenografia, expediente, secretaria em geral, etc.' },
    { id: '17.03', description: 'Planejamento, coordenação, programação ou organização técnica, financeira ou administrativa' },
    { id: '17.06', description: 'Propaganda e publicidade, inclusive promoção de vendas, planejamento de campanhas, etc.' },
    { id: '17.11', description: 'Organização de festas e recepções; bufê' },
    { id: '17.19', description: 'Contabilidade, inclusive serviços técnicos e auxiliares' },
    { id: '17.22', description: 'Cobrança em geral' },
    { id: '17.24', description: 'Telemarketing' },
    { id: '35.01', description: 'Serviços de reportagem, assessoria de imprensa, jornalismo e relações públicas' }
];
